### ISSUE TITLE
pomodoro.py function "add_callbacks" does not exist

### ISSUE THREAD

**Issue by quelotic** [Barbarossa93/Genome#3]
I can't seem to be able to run the qtile with the specific configuration because of the pomodoro script.
It seems that it's got a "self.add_callbacks" but no function is defined in it.

Removing the "add_callbacks" allows me to run qtile with the configuration.

**Comment by Barbarossa93** [comment]
Two possible things I can think of: Are you using the latest qtile-git? I should really put a note in the README about that. The other possibility is, did you also include the custom folder in my qtile directory? I made a slightly modified version of the builtin pomodoro widget.

**Comment by quelotic** [comment]
Yes yes, I'v got the custom folder also renamed all the hardcoded home directories to "~/".
I'd like to mention that the qtile-git is left way back on an april commit. The latest stable is since august.. There are plenty commits since that one but a quick overview did no suggest anything that could interfere with the problem im mentioning...

**Comment by Barbarossa93** [comment]
Are you on Arch? Because when you install a git package on the AUR it updates to the latest commit despite whatever version it may say. Otherwise, the only other thing I can think of is perhaps you're not importing something? I had to do `from libqtile import qtile` in order for the mouse_callback functions to work

**Comment by Barbarossa93** [comment]
Further, I'm not sure why you think the last qtile commit was last april. The last commit was literally [four hours ago](https://github.com/qtile/qtile/commit/7489b44d12af55d1a86ce219a0436e404002478c).

**Comment by quelotic** [comment]
You are right on that.. Haven't used many git packages that's why.. i just read the build. Ok maybe there's something with my qemu or the graphics drivers... I will give it another go on a fresh system and will be back with more information considering the matter.

**Comment by quelotic** [comment]
Alright, everything is working properly. Thank you for the quick answers!

**Comment by Barbarossa93** [comment]
Awesome, Glad you figured it out! Feel free to reach out with more questions if you have them
