### ISSUE TITLE
Adding top and bottom margins in widgets

### ISSUE THREAD

**Issue by UbadahJ** [Barbarossa93/Genome#7]
Hi!

Love your theme and was adapting it to my setup. Since my display parameters were much smaller than yours, I was updating the sizes to match as well. The only issue I am facing is sampled in the attached image; I can't work out how to add little margins in the widget.

![image](https://user-images.githubusercontent.com/26687928/107122946-a8cbc900-68bc-11eb-956a-a0b302b4868c.png)

So can you point me out how did you achieve that effect?

Thanks

**Comment by Barbarossa93** [comment]
I "cheated" and use eww to create a bar strip that cover up the parts above and below the rounded powerline symbols. Check my qtile's autostart file (it should have entries like `eww open border1; eww open border2` etc. Also look in `.config/eww/eww.xml`, that's where I define the strip bars. Some day, I'm hoping to patch qtile to allow drawing borders on the bar but unfortunately school is a top priority at the moment

**Comment by UbadahJ** [comment]
So that's why I couldn't find any reference to the paddings for the widget in the config files. 

Thanks, will work that out, or maybe if I got some time, I'll add borders to the widget myself
